###+-----------------------------------------------------------------------------------+
###|                                                                                   |
###| Generated by SLEC-2023.2/1056505  (Jul 18 2023)  linux64  S2307180103             |
###| on Sun Mar 24 15:39:50 2024.                                                      |
###|                                                                                   |
###| Restrictions concerning the use of Siemens SLEC                                   |
###| are covered in the license agreement. Distribution to third party                 |
###| is strictly prohibited.                                                           |
###|                                                                                   |
###+-----------------------------------------------------------------------------------+

###----------------------------------------------------------###
###      Default clock-domain assignments                    ###

set_clock_domain -clock _Ideal_Clk_ -polarity 0 impl.dummy_impl_in

###----------------------------------------------------------###
